# Generated by Django 3.1.4 on 2021-02-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='Maxsulot/')),
                ('nomi', models.CharField(max_length=25)),
                ('narxi', models.IntegerField()),
            ],
        ),
    ]
