# Generated by Django 3.1.4 on 2021-02-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_maxsulot_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
    ]
