# Generated by Django 3.1.4 on 2021-02-04 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_remove_category_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savatcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soni', models.IntegerField(default=1)),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.maxsulot')),
            ],
            options={
                'verbose_name_plural': 'Savatcha',
            },
        ),
    ]
