# Generated by Django 3.1.4 on 2021-02-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210204_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savatcha',
            name='soni',
        ),
        migrations.AddField(
            model_name='savatcha',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
